language: python

python:
  - "3.6.0"

before_script:
  - pip install -r requirements-test.txt
  - "make run-test-env-background"  # run dev flask server
  - sleep 5  # give Web server some time to bind to sockets, etc

script: make test-api

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6be1c3ba24a71df2a804
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always