---
- name: Copying the nginx config file for trumporate to /etc/nginx/sites-available/trumporate
  become: true
  template:
    src: etc/nginx/sites-available/trumporate.j2
    dest: /etc/nginx/sites-available/trumporate
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Create a symlink for /etc/nginx/sites-available/trumporate to /etc/nginx/sites-enabled
  become: true
  file:
    src: /etc/nginx/sites-available/trumporate
    dest: /etc/nginx/sites-enabled/trumporate
    state: link
    owner: root
    group: root
    mode: u=rwx,g=rwx,o=rwx
