---
- hosts: trumporate
  vars:
    username: ubuntu
    site_domain: trumporate.com
    letsencrypt_email: example@gmail.com
  roles:
    - role: install_packages
    - role: provision
    - role: systemd
    - role: nginx
    - role: ssl
    - role: deploy  # enable this after you have to update the server code
  